# Майнор "Интеллектуальный анализ данных", Введение в Анализ данных (ВШЭ)
## Домашнее задание №1

__Дата выдачи__: 28.01.2016

__Дедлайн__: 23:59 10.01.2016

Задание состоит в том, чтобы дописать в этом ipython notebook тело для всех функций, чтобы они работали так, как указано в формулировке. 

### Не нужно создавать свои функции с другими названиями!
Точнее, ответ должна выдавать именно та функция, которая указана в задании. Промежуточные функции создавать, конечно, можно.

Готовый файл нужно переименовать в формате iad16\_SnapeS.ipynb (заменив фамилию «Snape» и первую букву имени «S» на свои) и прислать на [hse.minor.dm+16@gmail.com](hse.minor.dm+16@gmail.com), указав в теме «[HW1] SnapeS».

Мы настоятельно рекомендуем выполнять задание на своем компьютере. Для этого лучше всего создать отдельную папку, скопировать туда этот notebook, открыть консоль (например, в Windows8: Shift + правая кнопка мыши, выбрать "Открыть → Окно команд") и написать jupiter notebook. Тогда вы всегда будете знать, где находятся ваши файлы.

При выполнении на сервере не гарантируется его стабильная работа, и ваш код смогут видеть другие студенты. 

На всякий случай напоминаем, что списывать нехорошо. За это будет <s>выпорот</s> сурово наказан и тот, кто списал, и тот, кто у кого списали. Но надеемся, что таких случаев не будет

Если формулировка задания не ясна — пишите на почту курса или семинаристам лично. Мы с радостью поможем разобраться.

Непонятные термины рекомендуем гуглить :) 

А вот решения гуглить не рекомендуем: задания не очень сложные, и сделаны они в первую очередь для того, чтобы вы освоились с numpy и pandas. Без этого дальше изучать курс будет сложно.

__Каждое выполненное задание дает 1 балл.__

При решении задач нельзя пользоваться циклами и рекурсией.

In [1]:
import numpy as np

# во всех задачах запрещается использовать циклы и рекурсию!

__№1__.  Написать функцию, которая берет на вход прямоугольную матрицу $A$ размера m x n и превращает каждый ее столбец в дискретное распределение с помощью применения функции _softmax_:

$\text{softmax}(a_j) = \frac {\exp (a_j)}{\sum_i \exp(a_i)}$, где a --- столбец матрицы $A$.

Таким образом, в матрице, возвращенной функцией, сумма каждого столбца матрицы должна быть равна 1.

In [7]:
#Пример

Example
Input:
[[0 1]
 [1 2]]
Output:
[[ 0.26894142  0.26894142]
 [ 0.73105858  0.73105858]]


In [ ]:
def compute_softmax(A):
    

__№2__. Напишите функцию, принимающую на вход матрицу X и два массива i и j одинаковой длины n и возвращающую вектор np.array, состоящий из последовательности элементов [X[i[0], j[0]], X[i[1], j[1]], ..., X[i[n-1], j[n-1]]].

In [11]:
#Пример

Example
Input:
X = [[0 1]
 [1 2]]
i =  [0 0] j =  [0 1]
Output:
0 1


In [ ]:
def choose_elems(X, i, j):
    

__№3__. Написать функцию, которая берет на вход матрицу A размера m x n, вектор b длины m и вектор c длины n и возвращает матрицу, составленную из блоков:

$\begin{pmatrix} A & b \\  c^T& 0 \end{pmatrix}$ = 

$\begin{pmatrix} a_{00} & a_{01} & \dots &a_{0,n-1} & b_0 \\ 
a_{10} & a_{11} & \dots &a_{1,n-1} & b_1 \\
 &&\dots& \\
a_{m-1,0} & a_{m-1,1} & \dots &a_{m-1,n-1} & b_{m-1} \\ 
c_0 & c_1 & \dots & c_{n-1 }& 0 \end{pmatrix}$

Будем считать, что матрица A может быть очень большой, поэтому выделять дополнительную память размера, сопоставимого с размером матрицы, нельзя.

In [12]:
#Пример

Example
Input:
A = [[0 1]
 [1 2]]
b =  [8 9] c =  [7 3]
Output:
[[0 1 8]
 [1 2 9]
 [7 3 0]]


In [ ]:
def construct_matrix(A, b, c):
    

__№4__. Даны две небольшие бинарные матрицы $A$ размера $m \times n$ и $B$ размера $n \times k$. 
Написать функцию, возвращающую матрицу $C$ такую, что

$C_{ij} = \&_{s=1}^n (A_{is} \lor B_{sj})$.

Здесь $\&$ означает логическое умножение (and), а $\lor$ — дизъюнкцию (or).

In [14]:
#Пример

Example
Input:
A = [[False  True]
 [ True False]]
Input:
B = [[ True False]
 [False  True]]
Output:
[[ True False]
 [False  True]]


In [ ]:
def perform_logical_computation(A, B):
    

__№5__. Напишите функцию, принимающую на вход np.array размера n и возвращающую матрицу размера n + 1 x n + 1, у которой над главной даигональю стоят элементы массива (остальные элементы должны быть нулевыми). 

In [15]:
#Пример

Example
Input:
[[1 2]]
Output:
[[0 1 0]
 [0 0 2]
 [0 0 0]]


__№6__. Дана матрица объекты-признаки X размера n x m. Посчитать (квадратную) матрицу попарных корреляций между признаками C:

$C_{ij} = cor_{ij} = \frac {cov_{ij}}{\sqrt{cov_{ii}cov_{jj}}}$ 

$cov_{ij} = cov(X_i, X_j), \quad i,j = 0, \dots, m-1.$

$cov(\{x_0, \dots, x_{n-1}\}, \{y_0, \dots, y_{n-1}\}) = \frac 1 {n-1} \sum_{i=0} ^ {n-1} (x_i-\bar x) (y_i - \bar y)$.

$\bar x = mean(\{x_0, \dots, x_{n-1}\}) = \frac 1 n \sum_{i=0} ^ {n-1} x_i$

Нельзя использовать функции np.cov, np.corrcoef, np.correlate (их можно использовать для проверки правильности ответа)


In [ ]:
def compute_corr_matrix(X):
    

__№7__. Дан массив X (размерность неизвестна). Заменить все элементы, кратные 3, которые больше 0 и меньше 100, на среднее значение по массиву.

In [19]:
#Пример

Example
Input:
[[14 11 10  0 12]
 [ 9  4 13  8  3]
 [ 6 14 13  5  5]
 [ 8  1  6  7 12]]
Output:
[[14 11 10  0  8]
 [ 8  4 13  8  8]
 [ 8 14 13  5  5]
 [ 8  1  8  7  8]]


In [20]:
import pandas as pd

Для выполнения заданий по pandas понадобится файл _countries.csv_: [https://goo.gl/AQqxaR](https://goo.gl/AQqxaR) --- тут его нужно скачать! Чтобы загрузить файл в jupiter, на странице с ноутбуками нажмите Upload, найдите на компьютере файл, снов анажмите upload.

In [22]:
#Загрузите данные в notebook:





__№8__. Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает ответ на следующий вопрос (строка).

Найдите страну, у которой наибольшее ВВП среди стран площадью меньше 200 или население меньше 10000 (или — не исключающее).

In [ ]:
def find_country(df):
    

__№9__.  Напишите функцию, которая берет на вход датафрейм pandas и возвращает датафрейм, в котором все пропуски заменены на среднее значение по столбцу. 

_Подсказка_: используйте функцию pandas.fillna()

In [ ]:
def fill_na(df):
    

__№10__.  Напишите функцию, которая берет на вход датафрейм pandas и число и возвращает ответ на вопрос (строка):

В какой стране ВВП (GDP) наиболее близок к указанной величине?

In [ ]:
def compare_GDP(df, gdp):
    

__№11__. __(Дополнительный). За выполнение этого задания можно получить +1 балл к общей сумме баллов (к 10)!__

Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает датафрейм с двумя колонками: буква алфавита и значение ВВП, усреднённое по всем странам, начинающимся с данной буквы.

Для решения задачи может понадобиться функция pandas.groupby, которую вы не успели пройти на семинаре. Поэтому задача и дополнительная.

In [ ]:
def compute_means_by_letters(df):
    